
output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

product_name: StickIt Rotary Encoder Module

product_version: V1.0

product_repo: https://github.com/xesscorp/StickIt-RotaryEncoder

topnav_title: StickIt Rotary Encoder Module Manual
# this appears on the top navigation bar next to the home button

site_title: StickIt Rotary Encoder Module Manual
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

stickit_mb: StickIt! Motherboard
xula2: XuLA2

company_shortname: XESS

company_name: XESS Corporation
# this appears in the footer

company_website: http://www.xess.com

company_help_page: http://www.xess.com/interact/contact

company_help_email: help@xess.com 

#manual_license: &copy;{{ site.time | date: "%Y"  }} {{site.company_name}}. All rights reserved. 
manual_license: 'Creative Commons License: <a href="http://creativecommons.org/licenses/by/4.0/legalcode">CC BY 4.0</a>'

github_editme_path:
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4005
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - Manual
# these are the files and directories that jekyll will exclude from the build

feedback_email: help@xess.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: true
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: manual_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: manual_sidebar

# these are defaults used for the frontmatter for these file types

sidebars:
- manual_sidebar

description: "Product manual for the StickIt! SmallButtons module from XESS Corp."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: https://github.com/xesscorp/StickIt-RotaryEncoder
